-- Overwrite existing vehicles
QBShared.Vehicles = {


  --- Larrys

  journey2 = {
    name = 'Journey II',
    brand = 'Zirconium',
    model = 'journey2',
    price = 45000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `journey2`,
    shop = 'larrys',
  },
  surfer = {
    name = 'Surfer',
    brand = 'BF',
    model = 'surfer',
    price = 9000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `surfer`,
    shop = 'larrys',
  },
  surfer3 = {
    name = 'Surfer Custom',
    brand = 'BF',
    model = 'surfer3',
    price = 19000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `surfer3`,
    shop = 'larrys',
  },
  camper = {
    name = 'Camper',
    brand = 'BF',
    model = 'camper',
    price = 19000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `camper`,
    shop = 'larrys',
  },
  boattrailer = {
    name = 'Boat trailer',
    brand = 'BF',
    model = 'boattrailer',
    price = 19000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `boattrailer`,
    shop = 'larrys',
  },


  --- PDM, Premium Deluxe Motors,

  blista2 = {
    name = 'Blista Compact',
    brand = 'Dinka',
    model = 'blista2',
    price = 18950,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `blista2`,
    shop = 'pdm',
  },
  weevil = {
    name = 'Weevil',
    brand = 'BF',
    model = 'weevil',
    price = 9000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `weevil`,
    shop = 'pdm',
  },
  issi3 = {
    name = 'Issi Classic',
    brand = 'Weeny',
    model = 'issi3',
    price = 7000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `issi3`,
    shop = 'pdm',
  },
  rhapsody = {
    name = 'Rhapsody',
    brand = 'Declasse',
    model = 'rhapsody',
    price = 10000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `rhapsody`,
    shop = 'pdm',
  },
  vigero = {
    name = 'Vigero',
    brand = 'Declasse',
    model = 'vigero',
    price = 26000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `vigero`,
    shop = 'pdm',
  },
  gauntlet3 = {
    name = 'Classic Gauntlet',
    brand = 'Bravado',
    model = 'gauntlet3',
    price = 30000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `gauntlet3`,
    shop = 'pdm',
  },
  dukes = {
    name = 'Dukes',
    brand = 'Imponte',
    model = 'dukes',
    price = 30000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `dukes`,
    shop = 'pdm',
  },
  vamos = {
    name = 'Vamos',
    brand = 'Declasse',
    model = 'vamos',
    price = 25000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `vamos`,
    shop = 'pdm',
  },
  phoenix = {
    name = 'Phoenix',
    brand = 'Imponte',
    model = 'phoenix',
    price = 26000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `phoenix`,
    shop = 'pdm',
  },
  ratloader2 = {
    name = 'Rat Truck',
    brand = 'Bravado',
    model = 'ratloader2',
    price = 30000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `ratloader2`,
    shop = 'pdm',
  },
  yosemite = {
    name = 'Yosemite',
    brand = 'Declasse',
    model = 'yosemite',
    price = 24000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `yosemite`,
    shop = 'pdm',
  },
  yosemite2 = {
    name = 'Yosemite',
    brand = 'Declasse',
    model = 'yosemite2',
    price = 50000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `yosemite2`,
    shop = 'pdm',
  },
  picador = {
    name = 'Picador',
    brand = 'Cheval',
    model = 'picador',
    price = 30000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `picador`,
    shop = 'pdm',
  },
  slamvan = {
    name = 'Slam Van',
    brand = 'Vapid',
    model = 'slamvan',
    price = 30000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `slamvan`,
    shop = 'pdm',
  },
  tornado = {
    name = 'Tornado',
    brand = 'Declasse',
    model = 'tornado',
    price = 21000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado`,
    shop = 'pdm',
  },
  tornado2 = {
    name = 'Tornado Convertible',
    brand = 'Declasse',
    model = 'tornado2',
    price = 22000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado2`,
    shop = 'pdm',
  },
  tornado5 = {
    name = 'Tornado Custom',
    brand = 'Declasse',
    model = 'tornado5',
    price = 22000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado5`,
    shop = 'pdm',
  },
  tampa = {
    name = 'Tampa',
    brand = 'Declasse',
    model = 'tampa',
    price = 30000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `tampa`,
    shop = 'pdm',
  },
  tulip = {
    name = 'Tulip',
    brand = 'Declasse',
    model = 'tulip',
    price = 33000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `tulip`,
    shop = 'pdm',
  },
  tulip2 = {
    name = 'Tulip M-100',
    brand = 'Declasse',
    model = 'tulip2',
    price = 28000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `tulip2`,
    shop = 'pdm',
  },
  tahoma = {
    name = 'Tahoma Coupe',
    brand = 'Declasse',
    model = 'tahoma',
    price = 28000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `tahoma`,
    shop = 'pdm',
  },
  ruiner = {
    name = 'Ruiner',
    brand = 'Declasse',
    model = 'ruiner',
    price = 28000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `ruiner`,
    shop = 'pdm',
  },
  dominator8 = {
    name = 'Dominator GTT',
    brand = 'Vapid',
    model = 'dominator8',
    price = 30000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `dominator8`,
    shop = 'pdm',
  },
  faction = {
    name = 'Faction',
    brand = 'Declasse',
    model = 'faction',
    price = 28000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `faction`,
    shop = 'pdm',
  },
  faction2 = {
    name = 'Faction Custom',
    brand = 'Declasse',
    model = 'faction2',
    price = 38000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `faction2`,
    shop = 'pdm',
  },
  sabregt = {
    name = 'Sabre GT Turbo',
    brand = 'Declasse',
    model = 'sabregt',
    price = 23000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `sabregt`,
    shop = 'pdm',
  },
  greenwood = {
    name = 'Greenwood',
    brand = 'Albany',
    model = 'greenwood',
    price = 32500,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `greenwood`,
    shop = 'pdm',
  },
  emperor = {
    name = 'Emperor',
    brand = 'Albany',
    model = 'emperor',
    price = 18250,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `emperor`,
    shop = 'pdm',
  },
  glendale = {
    name = 'Glendale',
    brand = 'Benefactor',
    model = 'glendale',
    price = 13400,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `glendale`,
    shop = 'pdm',
  },
  glendale2 = {
    name = 'Glendale Custom',
    brand = 'Benefactor',
    model = 'glendale2',
    price = 22000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `glendale2`,
    shop = 'pdm',
  },
  cheburek = {
    name = 'Cheburek',
    brand = 'Rune',
    model = 'cheburek',
    price = 12000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `cheburek`,
    shop = 'pdm',
  },
  regina = {
    name = 'Regina',
    brand = 'Dundreary',
    model = 'regina',
    price = 9000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `regina`,
    shop = 'pdm',
  },
  postlude = {
    name = 'Postlude',
    brand = 'Dinka',
    model = 'postlude',
    price = 50000,
    category = 'coupes',
    categoryLabel = 'Coupes',
    hash = `postlude`,
    shop = 'pdm',
  },
  manana = {
    name = 'Manana',
    brand = 'Albany',
    model = 'manana',
    price = 12800,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `manana`,
    shop = 'pdm',
  },
  manana2 = {
    name = 'Manana Custom',
    brand = 'Albany',
    model = 'manana2',
    price = 24000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `manana2`,
    shop = 'pdm',
  },
  peyote = {
    name = 'Peyote',
    brand = 'Vapid',
    model = 'peyote',
    price = 23500,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `peyote`,
    shop = 'pdm',
  },
  peyote2 = {
    name = 'Peyote Gasser',
    brand = 'Vapid',
    model = 'peyote2',
    price = 49000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `peyote2`,
    shop = 'pdm',
  },
  peyote3 = {
    name = 'Peyote Custom',
    brand = 'Vapid',
    model = 'peyote3',
    price = 37500,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `peyote3`,
    shop = 'pdm',
  },
  michelli = {
    name = 'Michelli GT',
    brand = 'Lampadati',
    model = 'michelli',
    price = 30000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `michelli`,
    shop = 'pdm',
  },
  pigalle = {
    name = 'Pigalle',
    brand = 'Lampadati',
    model = 'pigalle',
    price = 72000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `pigalle`,
    shop = 'pdm',
  },
  nebula = {
    name = 'Nebula',
    brand = 'Vulcar',
    model = 'nebula',
    price = 22000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `nebula`,
    shop = 'pdm',
  },
  fagaloa = {
    name = 'Fagaloa',
    brand = 'Vulcar',
    model = 'fagaloa',
    price = 13000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `fagaloa`,
    shop = 'pdm',
  },
  zion3 = {
    name = 'Zion Classic',
    brand = 'Übermacht',
    model = 'zion3',
    price = 45000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `zion3`,
    shop = 'pdm',
  },
  dynasty = {
    name = 'Dynasty',
    brand = 'Weeny',
    model = 'dynasty',
    price = 25000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `dynasty`,
    shop = 'pdm',
  },
  warrener = {
    name = 'Warrener',
    brand = 'Vulcar',
    model = 'warrener',
    price = 30000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `warrener`,
    shop = 'pdm',
  },
  warrener2 = {
    name = 'Warrener HKR',
    brand = 'Vulcar',
    model = 'warrener2',
    price = 27000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `warrener2`,
    shop = 'pdm',
  },
  sentinel3 = {
    name = 'Sentinel Classic',
    brand = 'Übermacht',
    model = 'sentinel3',
    price = 70000,
    category = 'coupes',
    categoryLabel = 'Coupes',
    hash = `sentinel3`,
    shop = 'pdm',
  },
  futo = {
    name = 'Futo',
    brand = 'Karin',
    model = 'futo',
    price = 17500,
    category = 'coupes',
    categoryLabel = 'Coupes',
    hash = `futo`,
    shop = 'pdm',
  },
  futo2 = {
    name = 'Futo GTX',
    brand = 'Karin',
    model = 'futo2',
    price = 24000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `futo2`,
    shop = 'pdm',
  },
  boor = {
    name = 'Seminole Frontier',
    brand = 'Karin',
    model = 'boor',
    price = 13000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `boor`,
    shop = 'pdm',
  },
  speedo = {
    name = 'Speedo',
    brand = 'Vapid',
    model = 'speedo',
    price = 10000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `speedo`,
    shop = 'pdm',
  },
  speedo4 = {
    name = 'Speedo Custom',
    brand = 'Vapid',
    model = 'speedo4',
    price = 15000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `speedo4`,
    shop = 'pdm',
  },
  burrito3 = {
    name = 'Burrito',
    brand = 'Declasse',
    model = 'burrito3',
    price = 12000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `burrito3`,
    shop = 'pdm',
  },
  youga2 = {
    name = 'Youga Classic',
    brand = 'Bravado',
    model = 'youga2',
    price = 14500,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `youga2`,
    shop = 'pdm',
  },
  club = {
    name = 'Club',
    brand = 'BF',
    model = 'club',
    price = 8000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `club`,
    shop = 'pdm',
  },
  brioso2 = {
    name = 'Brioso 300',
    brand = 'Grotti',
    model = 'brioso2',
    price = 12000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `brioso2`,
    shop = 'pdm',
  },
  brioso3 = {
    name = 'Brioso 300 Widebody',
    brand = 'Grotti',
    model = 'brioso3',
    price = 45000,
    category = 'compacts',
    categoryLabel = 'Compacts',
    hash = `brioso3`,
    shop = 'pdm',
  },
  buccaneer = {
    name = 'Buccaneer',
    brand = 'Albany',
    model = 'buccaneer',
    price = 22000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `buccaneer`,
    shop = 'pdm',
  },
  buccaneer2 = {
    name = 'Buccaneer Rider',
    brand = 'Albany',
    model = 'buccaneer2',
    price = 24500,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `buccaneer2`,
    shop = 'pdm',
  },
  voodoo = {
    name = 'Voodoo',
    brand = 'Declasse',
    model = 'voodoo',
    price = 35000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `voodoo`,
    shop = 'pdm',
  },
  retinue = {
    name = 'Retinue',
    brand = 'Vapid',
    model = 'retinue',
    price = 68000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `retinue`,
    shop = 'pdm',
  },
  retinue2 = {
    name = 'Retinue MKII',
    brand = 'Vapid',
    model = 'retinue2',
    price = 58000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `retinue2`,
    shop = 'pdm',
  },
  sabregt2 = {
    name = 'Sabre GT Turbo Custom',
    brand = 'Declasse',
    model = 'sabregt2',
    price = 56500,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `sabregt2`,
    shop = 'pdm',
  },
  savestra = {
    name = 'Savestra',
    brand = 'Annis',
    model = 'savestra',
    price = 67000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `savestra`,
    shop = 'pdm',
  },
  sentinel4 = {
    name = 'Sentinel Classic Widebody',
    brand = 'Übermacht',
    model = 'sentinel4',
    price = 140000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `sentinel4`,
    shop = 'pdm',
  },
  stalion = {
    name = 'Stallion',
    brand = 'Declasse',
    model = 'stalion',
    price = 53000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `stalion`,
    shop = 'pdm',
  },
  impaler = {
    name = 'Impaler',
    brand = 'Declasse',
    model = 'impaler',
    price = 29000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `impaler`,
    shop = 'pdm',
  },
  brigham = {
    name = 'Brigham',
    brand = 'Albany',
    model = 'brigham',
    price = 25000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `brigham`,
    shop = 'pdm',
  },


  --- PLM, Premium Luxury Motors

  broadway = {
    name = 'Broadway',
    brand = 'Classique',
    model = 'broadway',
    price = 75000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `broadway`,
    shop = 'luxury',
  },
  btype = {
    name = 'Roosevelt',
    brand = 'Albany',
    model = 'btype',
    price = 75000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `btype`,
    shop = 'luxury',
  },
  btype2 = {
    name = 'Franken Stange',
    brand = 'Albany',
    model = 'btype2',
    price = 149000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `btype2`,
    shop = 'luxury',
  },
  btype3 = {
    name = 'Roosevelt Valor',
    brand = 'Albany',
    model = 'btype3',
    price = 89000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `btype3`,
    shop = 'luxury',
  },
  casco = {
    name = 'Casco',
    brand = 'Lampadati',
    model = 'casco',
    price = 100000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `casco`,
    shop = 'luxury',
  },
  cheetah2 = {
    name = 'Cheetah Classic',
    brand = 'Grotti',
    model = 'cheetah2',
    price = 195000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `cheetah2`,
    shop = 'luxury',
  },
  chino = {
    name = 'Chino',
    brand = 'Vapid',
    model = 'chino',
    price = 55000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `chino`,
    shop = 'luxury',
  },
  chino2 = {
    name = 'Chino Convertible',
    brand = 'Vapid',
    model = 'chino2',
    price = 55000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `chino2`,
    shop = 'luxury',
  },
  clique = {
    name = 'Clique',
    brand = 'Vapid',
    model = 'clique',
    price = 60000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `clique`,
    shop = 'luxury',
  },
  clique2 = {
    name = 'Clique Wagon',
    brand = 'Vapid',
    model = 'clique2',
    price = 50000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `clique2`,
    shop = 'luxury',
  },
  coquette2 = {
    name = 'Coquette Classic',
    brand = 'Invetero',
    model = 'coquette2',
    price = 135000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `coquette2`,
    shop = 'luxury',
  },
  coquette3 = {
    name = 'Coquette BlackFin',
    brand = 'Invetero',
    model = 'coquette3',
    price = 145000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `coquette3`,
    shop = 'luxury',
  },
  ellie = {
    name = 'Ellie',
    brand = 'Vapid',
    model = 'ellie',
    price = 130000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `ellie`,
    shop = 'luxury',
  },
  eudora = {
    name = 'Eudora',
    brand = 'Willard',
    model = 'eudora',
    price = 60000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `eudora`,
    shop = 'luxury',
  },
  feltzer3 = {
    name = 'Stirling GT',
    brand = 'Benefactor',
    model = 'feltzer3',
    price = 115000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `feltzer3`,
    shop = 'luxury',
  },
  formula = {
    name = 'PR4 (kit-car)',
    brand = 'Progen / Dinka',
    model = 'formula',
    price = 250000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `formula`,
    shop = 'luxury',
  },
  gauntlet5 = {
    name = 'Gauntlet Classic Custom',
    brand = 'Bravado',
    model = 'gauntlet5',
    price = 75000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `gauntlet5`,
    shop = 'luxury',
  },
  gt500 = {
    name = 'GT500',
    brand = 'Grotti',
    model = 'gt500',
    price = 130000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `gt500`,
    shop = 'luxury',
  },
  hermes = {
    name = 'Hermes',
    brand = 'Albany',
    model = 'hermes',
    price = 65000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `hermes`,
    shop = 'luxury',
  },
  hotknife = {
    name = 'Hotknife',
    brand = 'Vapid',
    model = 'hotknife',
    price = 60000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `hotknife`,
    shop = 'luxury',
  },
  hustler = {
    name = 'Hustler',
    brand = 'Vapid',
    model = 'hustler',
    price = 65000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `hustler`,
    shop = 'luxury',
  },
  imperator = {
    name = 'Imperator',
    brand = 'Vapid',
    model = 'imperator',
    price = 85000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `imperator`,
    shop = 'luxury',
  },
  jb7002 = {
    name = 'JB 700W',
    brand = 'Dewbauchee',
    model = 'jb7002',
    price = 64000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `jb7002`,
    shop = 'luxury',
  },
  mamba = {
    name = 'Mamba',
    brand = 'Declasse',
    model = 'mamba',
    price = 140000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `mamba`,
    shop = 'luxury',
  },
  monroe = {
    name = 'Monroe',
    brand = 'Pegassi',
    model = 'monroe',
    price = 115000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `monroe`,
    shop = 'luxury',
  },
  nightshade = {
    name = 'Nightshade',
    brand = 'Imponte',
    model = 'nightshade',
    price = 65000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `nightshade`,
    shop = 'luxury',
  },
  omnis = {
    name = 'Omnis',
    brand = 'Wow',
    model = 'omnis',
    price = 90000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `omnis`,
    shop = 'luxury',
  },
  rapidgt3 = {
    name = 'Rapid GT Classic',
    brand = 'Dewbauchee',
    model = 'rapidgt3',
    price = 90000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `rapidgt3`,
    shop = 'luxury',
  },
  stafford = {
    name = 'Stafford',
    brand = 'Enus',
    model = 'stafford',
    price = 130000,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `stafford`,
    shop = 'luxury',
  },
  stinger = {
    name = 'Stinger',
    brand = 'Grotti',
    model = 'stinger',
    price = 51500,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `stinger`,
    shop = 'luxury',
  },
  stingergt = {
    name = 'Stinger GT',
    brand = 'Grotti',
    model = 'stingergt',
    price = 70000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `stingergt`,
    shop = 'luxury',
  },
  swinger = {
    name = 'Swinger',
    brand = 'Ocelot',
    model = 'swinger',
    price = 221000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `swinger`,
    shop = 'luxury',
  },
  torero = {
    name = 'Torero',
    brand = 'Pegassi',
    model = 'torero',
    price = 84000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `torero`,
    shop = 'luxury',
  },
  tropos = {
    name = 'Tropos Rallye',
    brand = 'Lampadati',
    model = 'tropos',
    price = 65000,
    category = 'sports',
    categoryLabel = 'Sports',
    hash = `tropos`,
    shop = 'luxury',
  },
  virgo = {
    name = 'Virgo',
    brand = 'Albany',
    model = 'virgo',
    price = 75000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `virgo`,
    shop = 'luxury',
  },
  virgo2 = {
    name = 'Virgo Classic',
    brand = 'Dundreary',
    model = 'virgo2',
    price = 75000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `virgo2`,
    shop = 'luxury',
  },
  virgo3 = {
    name = 'Virgo Classic Custom',
    brand = 'Dundreary',
    model = 'virgo3',
    price = 85000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `virgo3`,
    shop = 'luxury',
  },
  viseris = {
    name = 'Viseris',
    brand = 'Lampadati',
    model = 'viseris',
    price = 210000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `viseris`,
    shop = 'luxury',
  },
  z190 = {
    name = '190Z',
    brand = 'Karin',
    model = 'z190',
    price = 78000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `z190`,
    shop = 'luxury',
  },
  ztype = {
    name = 'Z-Type',
    brand = 'Truffade',
    model = 'ztype',
    price = 270000,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `ztype`,
    shop = 'luxury',
  },


  --- sportsbikes, Rockford Hills Motorcycles

  fcr = {
    name = 'FCR 1000',
    brand = 'Pegassi',
    model = 'fcr',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `fcr`,
    shop = 'sportbikes',
  },
  fcr2 = {
    name = 'FCR 1000 Custom',
    brand = 'Pegassi',
    model = 'fcr2',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `fcr2`,
    shop = 'sportbikes',
  },
  pcj = {
    name = 'PCJ-600',
    brand = 'Shitzu',
    model = 'pcj',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `pcj`,
    shop = 'sportbikes',
  },
  ruffian = {
    name = 'Ruffian',
    brand = 'Pegassi',
    model = 'ruffian',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `ruffian`,
    shop = 'sportbikes',
  },
  vader = {
    name = 'Vader',
    brand = 'Shitzu',
    model = 'vader',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `vader`,
    shop = 'sportbikes',
  },


  --- choppers, Rockford Hills Motorcycles

  avarus = {
    name = 'Avarus',
    brand = 'LCC',
    model = 'avarus',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `avarus`,
    shop = 'choppers',
  },
  bagger = {
    name = 'Bagger',
    brand = 'Western',
    model = 'bagger',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `bagger`,
    shop = 'choppers',
  },
  chimera = {
    name = 'Chimera',
    brand = 'Nagasaki',
    model = 'chimera',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `chimera`,
    shop = 'choppers',
  },
  cliffhanger = {
    name = 'Cliffhanger',
    brand = 'Western',
    model = 'cliffhanger',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `cliffhanger`,
    shop = 'choppers',
  },
  daemon = {
    name = 'Daemon',
    brand = 'Western',
    model = 'daemon',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `daemon`,
    shop = 'choppers',
  },
  daemon2 = {
    name = 'Daemon Custom',
    brand = 'Western',
    model = 'daemon2',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `daemon2`,
    shop = 'choppers',
  },
  sovereign = {
    name = 'Sovereign',
    brand = 'Western',
    model = 'sovereign',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `sovereign`,
    shop = 'choppers',
  },
  wolfsbane = {
    name = 'Wolfsbane',
    brand = 'Western',
    model = 'wolfsbane',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `wolfsbane`,
    shop = 'choppers',
  },
  zombiea = {
    name = 'Zombie Bobber',
    brand = 'Western',
    model = 'zombiea',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `zombiea`,
    shop = 'choppers',
  },
  zombieb = {
    name = 'Zombie Chopper',
    brand = 'Western',
    model = 'zombieb',
    price = 35000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `zombieb`,
    shop = 'choppers',
  },


  --- helmuts,
  --- cars
  winky = {
    name = 'Winky',
    brand = 'Vapid',
    price = 150000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    model = 'winky',
    hash = `winky`,
    shop = 'helmuts',
  },
  bifta = {
    name = 'Bifta',
    brand = 'Annis',
    price = 15500,
    category = 'offroad',
    categoryLabel = 'Off Road',
    model = 'bifta',
    hash = `bifta`,
    shop = 'helmuts',
  },
  bodhi2 = {
    name = 'Bodhi',
    brand = 'Canis',
    model = 'bodhi2',
    price = 14000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `bodhi2`,
    shop = 'helmuts',
  },
  kalahari = {
    name = 'Kalahari',
    brand = 'Canis',
    model = 'kalahari',
    price = 14000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `kalahari`,
    shop = 'helmuts',
  },
  rancherxl = {
    name = 'Rancher XL',
    brand = 'Declasse',
    model = 'rancherxl',
    price = 24000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `rancherxl`,
    shop = 'helmuts',
  },
  rebel2 = {
    name = 'Rebel',
    brand = 'Vapid',
    model = 'rebel2',
    price = 20000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `rebel2`,
    shop = 'helmuts',
  },
  seminole2 = {
    name = 'Seminole Frontier',
    brand = 'Canis',
    model = 'seminole2',
    price = 13000,
    category = 'suvs',
    categoryLabel = 'SUVs',
    hash = `seminole2`,
    shop = 'helmuts',
  },
  yosemite3 = {
    name = 'Yosemite',
    brand = 'Declasse',
    model = 'yosemite3',
    price = 30000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `yosemite3`,
    shop = 'helmuts',
  },
  bfinjection = {
    name = 'Bf Injection',
    brand = 'Annis',
    price = 19000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    model = 'bfinjection',
    hash = `bfinjection`,
    shop = 'helmuts',
  },
  l35 = {
    name = 'Walton L35',
    brand = 'Declasse',
    price = 25000,
    category = 'offroad',
    categoryLabel = 'Off Road',
    model = 'l35',
    hash = `l35`,
    shop = 'helmuts',
  },

  --- Motorcycles
  enduro = {
    name = 'Enduro',
    brand = 'Dinka',
    model = 'enduro',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `enduro`,
    shop = 'helmuts',
  },
  manchez = {
    name = 'Manchez',
    brand = 'Maibatsu',
    model = 'manchez',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `manchez`,
    shop = 'helmuts',
  },
  manchez2 = {
    name = 'Manchez Scout',
    brand = 'Maibatsu',
    model = 'manchez2',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `manchez2`,
    shop = 'helmuts',
  },
  manchez3 = {
    name = 'Manchez Scout C',
    brand = 'Maibatsu',
    model = 'manchez3',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `manchez3`,
    shop = 'helmuts',
  },
  sanchez = {
    name = 'Sanchez Cross',
    brand = 'Maibatsu',
    model = 'sanchez',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `sanchez`,
    shop = 'helmuts',
  },
  sanchez2 = {
    name = 'Sanchez',
    brand = 'Maibatsu',
    model = 'sanchez2',
    price = 24000,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `sanchez2`,
    shop = 'helmuts',
  },


  --- rogers - Rogers Scrap Emporium

  dloader = {
    name = 'Duneloader',
    brand = 'Bravado',
    model = 'dloader',
    price = 4500,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `dloader`,
    shop = 'rogers',
  },
  dukes3 = {
    name = 'Dukes',
    brand = 'Imponte',
    model = 'dukes3',
    price = 4000,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `dukes3`,
    shop = 'rogers',
  },
  dune = {
    name = 'Dune Buggy',
    brand = 'Annis',
    price = 2400,
    category = 'offroad',
    categoryLabel = 'Off Road',
    model = 'dune',
    hash = `dune`,
    shop = 'rogers',
  },
  emperor2 = {
    name = 'Emperor',
    brand = 'Albany',
    model = 'emperor2',
    price = 3250,
    category = 'sedans',
    categoryLabel = 'Sedans',
    hash = `emperor2`,
    shop = 'rogers',
  },
  journey = {
    name = 'Journey',
    brand = 'Zirconium',
    model = 'journey',
    price = 7500,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `journey`,
    shop = 'rogers',
  },
  ratloader = {
    name = 'Ratloader',
    brand = 'Bravado',
    model = 'ratloader',
    price = 3000,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `ratloader`,
    shop = 'rogers',
  },
  rebel = {
    name = 'Rebel',
    brand = 'Vapid',
    model = 'rebel',
    price = 3500,
    category = 'offroad',
    categoryLabel = 'Off Road',
    hash = `rebel`,
    shop = 'rogers',
  },
  scrap = {
    name = 'Scraptruck',
    brand = 'Vapid',
    model = 'scrap',
    price = 3500,
    category = 'utility',
    categoryLabel = 'Utility',
    hash = `scrap`,
    shop = 'rogers',
  },
  surfer2 = {
    name = 'Surfer',
    brand = 'BF',
    model = 'surfer2',
    price = 2400,
    category = 'vans',
    categoryLabel = 'Vans',
    hash = `surfer2`,
    shop = 'rogers',
  },
  tornado3 = {
    name = 'Tornado Convertible',
    brand = 'Declasse',
    model = 'tornado3',
    price = 2400,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado3`,
    shop = 'rogers',
  },
  tornado4 = {
    name = 'Tornado Convertible',
    brand = 'Declasse',
    model = 'tornado4',
    price = 2400,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado4`,
    shop = 'rogers',
  },
  tornado6 = {
    name = 'Tornado Rat Rod',
    brand = 'Declasse',
    model = 'tornado6',
    price = 7500,
    category = 'sportsclassics',
    categoryLabel = 'Sports Classics',
    hash = `tornado6`,
    shop = 'rogers',
  },
  voodoo2 = {
    name = 'Voodoo',
    brand = 'Declasse',
    model = 'voodoo2',
    price = 2500,
    category = 'muscle',
    categoryLabel = 'Muscle',
    hash = `voodoo2`,
    shop = 'rogers',
  },
  ratbike = {
    name = 'Ratbike',
    brand = 'Western',
    model = 'ratbike',
    price = 3500,
    category = 'motorcycles',
    categoryLabel = 'Motorcycle',
    hash = `ratbike`,
    shop = 'rogers',
  },


  
  -- Emergency
  ambulance = {
    name = 'Ambulance',
    brand = 'Emergency',
    model = 'ambulance',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `ambulance`,
    shop = 'admin',
  },
  bcsochamp = {
    name = 'bcsochamp',
    brand = 'Emergency',
    model = 'bcsochamp',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcsochamp`,
    shop = 'admin',
  },
  dickgreenwd = {
    name = 'dickgreenwd',
    brand = 'Emergency',
    model = 'dickgreenwd',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dickgreenwd`,
    shop = 'admin',
  },
  dw_bcpd8 = {
    name = 'dw_bcpd8',
    brand = 'Emergency',
    model = 'dw_bcpd8',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_bcpd8`,
    shop = 'admin',
  },
  dw_bcsosheriff2 = {
    name = 'dw_bcsosheriff2',
    brand = 'Emergency',
    model = 'dw_bcsosheriff2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_bcsosheriff2`,
    shop = 'admin',
  },
  dw_bspony = {
    name = 'dw_bspony',
    brand = 'Emergency',
    model = 'dw_bspony',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_bspony`,
    shop = 'admin',
  },
  dw_bsseminolef = {
    name = 'dw_bsseminolef',
    brand = 'Emergency',
    model = 'dw_bsseminolef',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_bsseminolef`,
    shop = 'admin',
  },
  dw_chfbrick = {
    name = 'dw_chfbrick',
    brand = 'Emergency',
    model = 'dw_chfbrick',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_chfbrick`,
    shop = 'admin',
  },
  dw_fbifact = {
    name = 'dw_fbifact',
    brand = 'Emergency',
    model = 'dw_fbifact',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_fbifact`,
    shop = 'admin',
  },
  dw_fibesperanto = {
    name = 'dw_fibesperanto',
    brand = 'Emergency',
    model = 'dw_fibesperanto',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_fibesperanto`,
    shop = 'admin',
  },
  dw_fibrancher = {
    name = 'dw_fibrancher',
    brand = 'Emergency',
    model = 'dw_fibrancher',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_fibrancher`,
    shop = 'admin',
  },
  dw_g6caddy = {
    name = 'dw_g6caddy',
    brand = 'Emergency',
    model = 'dw_g6caddy',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_g6caddy`,
    shop = 'admin',
  },
  dw_hwayfact = {
    name = 'dw_hwayfact',
    brand = 'Emergency',
    model = 'dw_hwayfact',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_hwayfact`,
    shop = 'admin',
  },
  dw_hwayvig3 = {
    name = 'dw_hwayvig3',
    brand = 'Emergency',
    model = 'dw_hwayvig3',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_hwayvig3`,
    shop = 'admin',
  },
  dw_lguardold = {
    name = 'dw_lguardold',
    brand = 'Emergency',
    model = 'dw_lguardold',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_lguardold`,
    shop = 'admin',
  },
  dw_lguardsq = {
    name = 'dw_lguardsq',
    brand = 'Emergency',
    model = 'dw_lguardsq',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_lguardsq`,
    shop = 'admin',
  },
  dw_lspdb = {
    name = 'dw_lspdb',
    brand = 'Emergency',
    model = 'dw_lspdb',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_lspdb`,
    shop = 'admin',
  },
  dw_lssheriffvig3 = {
    name = 'dw_lssheriffvig3',
    brand = 'Emergency',
    model = 'dw_lssheriffvig3',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_lssheriffvig3`,
    shop = 'admin',
  },
  dw_noosebp4 = {
    name = 'dw_noosebp4',
    brand = 'Emergency',
    model = 'dw_noosebp4',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_noosebp4`,
    shop = 'admin',
  },
  dw_noosesea = {
    name = 'dw_noosesea',
    brand = 'Emergency',
    model = 'dw_noosesea',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_noosesea`,
    shop = 'admin',
  },
  dw_noosesea2 = {
    name = 'dw_noosesea2',
    brand = 'Emergency',
    model = 'dw_noosesea2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_noosesea2`,
    shop = 'admin',
  },
  dw_pcpdhermes = {
    name = 'dw_pcpdhermes',
    brand = 'Emergency',
    model = 'dw_pcpdhermes',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_pcpdhermes`,
    shop = 'admin',
  },
  dw_pcpdvig = {
    name = 'dw_pcpdvig',
    brand = 'Emergency',
    model = 'dw_pcpdvig',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_pcpdvig`,
    shop = 'admin',
  },
  dw_polboxville = {
    name = 'dw_polboxville',
    brand = 'Emergency',
    model = 'dw_polboxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_polboxville`,
    shop = 'admin',
  },
  dw_polbrigham4 = {
    name = 'dw_polbrigham4',
    brand = 'Emergency',
    model = 'dw_polbrigham4',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_polbrigham4`,
    shop = 'admin',
  },
  dw_polcomet = {
    name = 'dw_polcomet',
    brand = 'Emergency',
    model = 'dw_polcomet',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_polcomet`,
    shop = 'admin',
  },
  dw_policeuranus2 = {
    name = 'dw_policeuranus2',
    brand = 'Emergency',
    model = 'dw_policeuranus2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_policeuranus2`,
    shop = 'admin',
  },
  dw_policevig3 = {
    name = 'dw_policevig3',
    brand = 'Emergency',
    model = 'dw_policevig3',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_policevig3`,
    shop = 'admin',
  },
  dw_policevig32 = {
    name = 'dw_policevig32',
    brand = 'Emergency',
    model = 'dw_policevig32',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_policevig32`,
    shop = 'admin',
  },
  dw_polpony2 = {
    name = 'dw_polpony2',
    brand = 'Emergency',
    model = 'dw_polpony2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_polpony2`,
    shop = 'admin',
  },
  dw_prangerpat = {
    name = 'dw_prangerpat',
    brand = 'Emergency',
    model = 'dw_prangerpat',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_prangerpat`,
    shop = 'admin',
  },
  dw_sahpb = {
    name = 'dw_sahpb',
    brand = 'Emergency',
    model = 'dw_sahpb',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sahpb`,
    shop = 'admin',
  },
  dw_saprlguardme = {
    name = 'dw_saprlguardme',
    brand = 'Emergency',
    model = 'dw_saprlguardme',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_saprlguardme`,
    shop = 'admin',
  },
  dw_sasputil = {
    name = 'dw_sasputil',
    brand = 'Emergency',
    model = 'dw_sasputil',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sasputil`,
    shop = 'admin',
  },
  dw_sheriffb3 = {
    name = 'dw_sheriffb3',
    brand = 'Emergency',
    model = 'dw_sheriffb3',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffb3`,
    shop = 'admin',
  },
  dw_sheriffmoon = {
    name = 'dw_sheriffmoon',
    brand = 'Emergency',
    model = 'dw_sheriffmoon',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffmoon`,
    shop = 'admin',
  },
  dw_sheriffpatriot = {
    name = 'dw_sheriffpatriot',
    brand = 'Emergency',
    model = 'dw_sheriffpatriot',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffpatriot`,
    shop = 'admin',
  },
  dw_sheriffriata = {
    name = 'dw_sheriffriata',
    brand = 'Emergency',
    model = 'dw_sheriffriata',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffriata`,
    shop = 'admin',
  },
  dw_sheriffsadler = {
    name = 'dw_sheriffsadler',
    brand = 'Emergency',
    model = 'dw_sheriffsadler',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffsadler`,
    shop = 'admin',
  },
  dw_sheriffvalk = {
    name = 'dw_sheriffvalk',
    brand = 'Emergency',
    model = 'dw_sheriffvalk',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffvalk`,
    shop = 'admin',
  },
  dw_sheriffyos = {
    name = 'dw_sheriffyos',
    brand = 'Emergency',
    model = 'dw_sheriffyos',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sheriffyos`,
    shop = 'admin',
  },
  dw_sherranch = {
    name = 'dw_sherranch',
    brand = 'Emergency',
    model = 'dw_sherranch',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_sherranch`,
    shop = 'admin',
  },
  dw_ufesuv = {
    name = 'dw_ufesuv',
    brand = 'Emergency',
    model = 'dw_ufesuv',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_ufesuv`,
    shop = 'admin',
  },
  dw_umpony = {
    name = 'dw_umpony',
    brand = 'Emergency',
    model = 'dw_umpony',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_umpony`,
    shop = 'admin',
  },
  dw_vicechee = {
    name = 'dw_vicechee',
    brand = 'Emergency',
    model = 'dw_vicechee',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `dw_vicechee`,
    shop = 'admin',
  },
  fbigreenwd = {
    name = 'fbigreenwd',
    brand = 'Emergency',
    model = 'fbigreenwd',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fbigreenwd`,
    shop = 'admin',
  },
  fdlcamb2 = {
    name = 'fdlcamb2',
    brand = 'Emergency',
    model = 'fdlcamb2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdlcamb2`,
    shop = 'admin',
  },
  fdlcambold = {
    name = 'fdlcambold',
    brand = 'Emergency',
    model = 'fdlcambold',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdlcambold`,
    shop = 'admin',
  },
  fdlcboxville = {
    name = 'fdlcboxville',
    brand = 'Emergency',
    model = 'fdlcboxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdlcboxville`,
    shop = 'admin',
  },
  fdlcgranger = {
    name = 'fdlcgranger',
    brand = 'Emergency',
    model = 'fdlcgranger',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdlcgranger`,
    shop = 'admin',
  },
  fdlcsteed = {
    name = 'fdlcsteed',
    brand = 'Emergency',
    model = 'fdlcsteed',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdlcsteed`,
    shop = 'admin',
  },
  FireCrown1 = {
    name = 'FireCrown1',
    brand = 'Emergency',
    model = 'FireCrown1',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `FireCrown1`,
    shop = 'admin',
  },
  FireCrown2 = {
    name = 'FireCrown2',
    brand = 'Emergency',
    model = 'FireCrown2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `FireCrown2`,
    shop = 'admin',
  },
  hwayruiner = {
    name = 'hwayruiner',
    brand = 'Emergency',
    model = 'hwayruiner',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `hwayruiner`,
    shop = 'admin',
  },
  lafrance = {
    name = 'lafrance',
    brand = 'Emergency',
    model = 'lafrance',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lafrance`,
    shop = 'admin',
  },
  lcambre = {
    name = 'lcambre',
    brand = 'Emergency',
    model = 'lcambre',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcambre`,
    shop = 'admin',
  },
  lcpdb = {
    name = 'lcpdb',
    brand = 'Emergency',
    model = 'lcpdb',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdb`,
    shop = 'admin',
  },
  lcpdbob = {
    name = 'lcpdbob',
    brand = 'Emergency',
    model = 'lcpdbob',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdbob`,
    shop = 'admin',
  },
  lcpdboxville = {
    name = 'lcpdboxville',
    brand = 'Emergency',
    model = 'lcpdboxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdboxville`,
    shop = 'admin',
  },
  lcpdesp = {
    name = 'lcpdesp',
    brand = 'Emergency',
    model = 'lcpdesp',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdesp`,
    shop = 'admin',
  },
  lcpdfaggio = {
    name = 'lcpdfaggio',
    brand = 'Emergency',
    model = 'lcpdfaggio',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdfaggio`,
    shop = 'admin',
  },
  lcpdmerit = {
    name = 'lcpdmerit',
    brand = 'Emergency',
    model = 'lcpdmerit',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdmerit`,
    shop = 'admin',
  },
  lcpdranch = {
    name = 'lcpdranch',
    brand = 'Emergency',
    model = 'lcpdranch',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdranch`,
    shop = 'admin',
  },
  lcpdriata = {
    name = 'lcpdriata',
    brand = 'Emergency',
    model = 'lcpdriata',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdriata`,
    shop = 'admin',
  },
  lcpdshark = {
    name = 'lcpdshark',
    brand = 'Emergency',
    model = 'lcpdshark',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdshark`,
    shop = 'admin',
  },
  lcpdstockade = {
    name = 'lcpdstockade',
    brand = 'Emergency',
    model = 'lcpdstockade',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdstockade`,
    shop = 'admin',
  },
  lcpdtulip = {
    name = 'lcpdtulip',
    brand = 'Emergency',
    model = 'lcpdtulip',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lcpdtulip`,
    shop = 'admin',
  },
  lspdbri = {
    name = 'lspdbri',
    brand = 'Emergency',
    model = 'lspdbri',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspdbri`,
    shop = 'admin',
  },
  lspdbri2 = {
    name = 'lspdbri2',
    brand = 'Emergency',
    model = 'lspdbri2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspdbri2`,
    shop = 'admin',
  },
  lssdtulipum = {
    name = 'lssdtulipum',
    brand = 'Emergency',
    model = 'lssdtulipum',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lssdtulipum`,
    shop = 'admin',
  },
  mspgreenwd = {
    name = 'mspgreenwd',
    brand = 'Emergency',
    model = 'mspgreenwd',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `mspgreenwd`,
    shop = 'admin',
  },
  newfiretruk = {
    name = 'newfiretruk',
    brand = 'Emergency',
    model = 'newfiretruk',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `newfiretruk`,
    shop = 'admin',
  },
  poladmiral = {
    name = 'poladmiral',
    brand = 'Emergency',
    model = 'poladmiral',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `poladmiral`,
    shop = 'admin',
  },
  polgreenwd = {
    name = 'polgreenwd',
    brand = 'Emergency',
    model = 'polgreenwd',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `polgreenwd`,
    shop = 'admin',
  },
  ptornado = {
    name = 'ptornado',
    brand = 'Emergency',
    model = 'ptornado',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `ptornado`,
    shop = 'admin',
  },
  sahpbri = {
    name = 'sahpbri',
    brand = 'Emergency',
    model = 'sahpbri',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahpbri`,
    shop = 'admin',
  },
  shergreenwd = {
    name = 'shergreenwd',
    brand = 'Emergency',
    model = 'shergreenwd',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `shergreenwd`,
    shop = 'admin',
  },
  sheriffretro = {
    name = 'sheriffretro',
    brand = 'Emergency',
    model = 'sheriffretro',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sheriffretro`,
    shop = 'admin',
  },
  sheriffretro2 = {
    name = 'sheriffretro2',
    brand = 'Emergency',
    model = 'sheriffretro2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sheriffretro2`,
    shop = 'admin',
  },
  sheriffsparrow = {
    name = 'sheriffsparrow',
    brand = 'Emergency',
    model = 'sheriffsparrow',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sheriffsparrow`,
    shop = 'admin',
  },
  sherifftrike = {
    name = 'sherifftrike',
    brand = 'Emergency',
    model = 'sherifftrike',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sherifftrike`,
    shop = 'admin',
  },
  uazam = {
    name = 'uazam',
    brand = 'Emergency',
    model = 'uazam',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `uazam`,
    shop = 'admin',
  },
  uh1nasa = {
    name = 'uh1nasa',
    brand = 'Emergency',
    model = 'uh1nasa',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `uh1nasa`,
    shop = 'admin',
  },
  umkadmiral = {
    name = 'umkadmiral',
    brand = 'Emergency',
    model = 'umkadmiral',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `umkadmiral`,
    shop = 'admin',
  },
  ward = {
    name = 'ward',
    brand = 'Emergency',
    model = 'ward',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `ward`,
    shop = 'admin',
  },
  zilfire = {
    name = 'zilfire',
    brand = 'Emergency',
    model = 'zilfire',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `zilfire`,
    shop = 'admin',
  },
  bcso_champion = {
    name = 'bcso_champion',
    brand = 'Emergency',
    model = 'bcso_champion',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_champion`,
    shop = 'admin',
  },
  cid_greenwood = {
    name = 'cid_greenwood',
    brand = 'Emergency',
    model = 'cid_greenwood',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_greenwood`,
    shop = 'admin',
  },
  sahp_torero = {
    name = 'sahp_torero',
    brand = 'Emergency',
    model = 'sahp_torero',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_torero`,
    shop = 'admin',
  },
  bcso_rancher = {
    name = 'bcso_rancher',
    brand = 'Emergency',
    model = 'bcso_rancher',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_rancher`,
    shop = 'admin',
  },
  admin_pony = {
    name = 'admin_pony',
    brand = 'Emergency',
    model = 'admin_pony',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `admin_pony`,
    shop = 'admin',
  },
  admin_seminole = {
    name = 'admin_seminole',
    brand = 'Emergency',
    model = 'admin_seminole',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `admin_seminole`,
    shop = 'admin',
  },
  admin_brick = {
    name = 'admin_brick',
    brand = 'Emergency',
    model = 'admin_brick',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `admin_brick`,
    shop = 'admin',
  },
  cid_faction = {
    name = 'cid_faction',
    brand = 'Emergency',
    model = 'cid_faction',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_faction`,
    shop = 'admin',
  },
  cid_esperanto = {
    name = 'cid_esperanto',
    brand = 'Emergency',
    model = 'cid_esperanto',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_esperanto`,
    shop = 'admin',
  },
  cid_rancherxl = {
    name = 'cid_rancherxl',
    brand = 'Emergency',
    model = 'cid_rancherxl',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_rancherxl`,
    shop = 'admin',
  },
  bbpr_caddy = {
    name = 'bbpr_caddy',
    brand = 'Emergency',
    model = 'bbpr_caddy',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_caddy`,
    shop = 'admin',
  },
  sahp_faction = {
    name = 'sahp_faction',
    brand = 'Emergency',
    model = 'sahp_faction',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_faction`,
    shop = 'admin',
  },
  sahp_vigero = {
    name = 'sahp_vigero',
    brand = 'Emergency',
    model = 'sahp_vigero',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_vigero`,
    shop = 'admin',
  },
  sacg_sadler = {
    name = 'sacg_sadler',
    brand = 'Emergency',
    model = 'sacg_sadler',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sacg_sadler`,
    shop = 'admin',
  },
  sacg_squire = {
    name = 'sacg_squire',
    brand = 'Emergency',
    model = 'sacg_squire',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sacg_squire`,
    shop = 'admin',
  },
  lspd_western2 = {
    name = 'lspd_western2',
    brand = 'Emergency',
    model = 'lspd_western2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_western2`,
    shop = 'admin',
  },
  bcso_vigero = {
    name = 'bcso_vigero',
    brand = 'Emergency',
    model = 'bcso_vigero',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_vigero`,
    shop = 'admin',
  },
  bbpr_mesa = {
    name = 'bbpr_mesa',
    brand = 'Emergency',
    model = 'bbpr_mesa',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_mesa`,
    shop = 'admin',
  },
  sacg_predator = {
    name = 'sacg_predator',
    brand = 'Emergency',
    model = 'sacg_predator',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sacg_predator`,
    shop = 'admin',
  },
  sacg_dingy = {
    name = 'sacg_dingy',
    brand = 'Emergency',
    model = 'sacg_dingy',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sacg_dingy`,
    shop = 'admin',
  },
  lspd_hermes = {
    name = 'lspd_hermes',
    brand = 'Emergency',
    model = 'lspd_hermes',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_hermes`,
    shop = 'admin',
  },
  bcso_mccracken = {
    name = 'bcso_mccracken',
    brand = 'Emergency',
    model = 'bcso_mccracken',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_mccracken`,
    shop = 'admin',
  },
  cid_boxville = {
    name = 'cid_boxville',
    brand = 'Emergency',
    model = 'cid_boxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_boxville`,
    shop = 'admin',
  },
  cid_brigham2 = {
    name = 'cid_brigham2',
    brand = 'Emergency',
    model = 'cid_brigham2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_brigham2`,
    shop = 'admin',
  },
  sahp_comet = {
    name = 'sahp_comet',
    brand = 'Emergency',
    model = 'sahp_comet',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_comet`,
    shop = 'admin',
  },
  cid_uranus = {
    name = 'cid_uranus',
    brand = 'Emergency',
    model = 'cid_uranus',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_uranus`,
    shop = 'admin',
  },
  lspd_vigero = {
    name = 'lspd_vigero',
    brand = 'Emergency',
    model = 'lspd_vigero',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_vigero`,
    shop = 'admin',
  },
  cid_vigero = {
    name = 'cid_vigero',
    brand = 'Emergency',
    model = 'cid_vigero',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_vigero`,
    shop = 'admin',
  },
  lspd_pony = {
    name = 'lspd_pony',
    brand = 'Emergency',
    model = 'lspd_pony',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_pony`,
    shop = 'admin',
  },
  bbpr_patriot = {
    name = 'bbpr_patriot',
    brand = 'Emergency',
    model = 'bbpr_patriot',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_patriot`,
    shop = 'admin',
  },
  lspd_western3 = {
    name = 'lspd_western3',
    brand = 'Emergency',
    model = 'lspd_western3',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_western3`,
    shop = 'admin',
  },
  sacg_mesa = {
    name = 'sacg_mesa',
    brand = 'Emergency',
    model = 'sacg_mesa',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sacg_mesa`,
    shop = 'admin',
  },
  bbpr_utility = {
    name = 'bbpr_utility',
    brand = 'Emergency',
    model = 'bbpr_utility',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_utility`,
    shop = 'admin',
  },
  bbpr_sanchez = {
    name = 'bbpr_sanchez',
    brand = 'Emergency',
    model = 'bbpr_sanchez',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_sanchez`,
    shop = 'admin',
  },
  cid_moonbeam = {
    name = 'cid_moonbeam',
    brand = 'Emergency',
    model = 'cid_moonbeam',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_moonbeam`,
    shop = 'admin',
  },
  hosers_patriot = {
    name = 'hosers_patriot',
    brand = 'Emergency',
    model = 'hosers_patriot',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `hosers_patriot`,
    shop = 'admin',
  },
  bcso_riata = {
    name = 'bcso_riata',
    brand = 'Emergency',
    model = 'bcso_riata',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_riata`,
    shop = 'admin',
  },
  bcso_sadler = {
    name = 'bcso_sadler',
    brand = 'Emergency',
    model = 'bcso_sadler',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_sadler`,
    shop = 'admin',
  },
  sahp_valkyrie = {
    name = 'sahp_valkyrie',
    brand = 'Emergency',
    model = 'sahp_valkyrie',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_valkyrie`,
    shop = 'admin',
  },
  bcso_yosemite = {
    name = 'bcso_yosemite',
    brand = 'Emergency',
    model = 'bcso_yosemite',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_yosemite`,
    shop = 'admin',
  },
  bbpr_rancherxl = {
    name = 'bbpr_rancherxl',
    brand = 'Emergency',
    model = 'bbpr_rancherxl',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_rancherxl`,
    shop = 'admin',
  },
  bbpr_450 = {
    name = 'bbpr_450',
    brand = 'Emergency',
    model = 'bbpr_450',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_450`,
    shop = 'admin',
  },
  cid_pony = {
    name = 'cid_pony',
    brand = 'Emergency',
    model = 'cid_pony',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_pony`,
    shop = 'admin',
  },
  cid_cheetah = {
    name = 'cid_cheetah',
    brand = 'Emergency',
    model = 'cid_cheetah',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_cheetah`,
    shop = 'admin',
  },
  cid_greenwood2 = {
    name = 'cid_greenwood2',
    brand = 'Emergency',
    model = 'cid_greenwood2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_greenwood2`,
    shop = 'admin',
  },
  fdsa_speedo = {
    name = 'fdsa_speedo',
    brand = 'Emergency',
    model = 'fdsa_speedo',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_speedo`,
    shop = 'admin',
  },
  fdsa_sadlerbox = {
    name = 'fdsa_sadlerbox',
    brand = 'Emergency',
    model = 'fdsa_sadlerbox',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_sadlerbox`,
    shop = 'admin',
  },
  fdsa_boxville = {
    name = 'fdsa_boxville',
    brand = 'Emergency',
    model = 'fdsa_boxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_boxville`,
    shop = 'admin',
  },
  fdsa_granger = {
    name = 'fdsa_granger',
    brand = 'Emergency',
    model = 'fdsa_granger',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_granger`,
    shop = 'admin',
  },
  fdsa_steed = {
    name = 'fdsa_steed',
    brand = 'Emergency',
    model = 'fdsa_steed',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_steed`,
    shop = 'admin',
  },
  fdsa_crown = {
    name = 'fdsa_crown',
    brand = 'Emergency',
    model = 'fdsa_crown',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_crown`,
    shop = 'admin',
  },
  fdsa_crown2 = {
    name = 'fdsa_crown2',
    brand = 'Emergency',
    model = 'fdsa_crown2',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_crown2`,
    shop = 'admin',
  },
  sahp_ruiner = {
    name = 'sahp_ruiner',
    brand = 'Emergency',
    model = 'sahp_ruiner',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_ruiner`,
    shop = 'admin',
  },
  fdsa_lafrance = {
    name = 'fdsa_lafrance',
    brand = 'Emergency',
    model = 'fdsa_lafrance',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `fdsa_lafrance`,
    shop = 'admin',
  },
  ems_regina = {
    name = 'ems_regina',
    brand = 'Emergency',
    model = 'ems_regina',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `ems_regina`,
    shop = 'admin',
  },
  policeb = {
    name = 'policeb',
    brand = 'Emergency',
    model = 'policeb',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `policeb`,
    shop = 'admin',
  },
  lspd_western = {
    name = 'lspd_western',
    brand = 'Emergency',
    model = 'lspd_western',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_western`,
    shop = 'admin',
  },
  bcso_bobcat = {
    name = 'bcso_bobcat',
    brand = 'Emergency',
    model = 'bcso_bobcat',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_bobcat`,
    shop = 'admin',
  },
  lspd_boxville = {
    name = 'lspd_boxville',
    brand = 'Emergency',
    model = 'lspd_boxville',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_boxville`,
    shop = 'admin',
  },
  sahp_esperanto = {
    name = 'sahp_esperanto',
    brand = 'Emergency',
    model = 'sahp_esperanto',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_esperanto`,
    shop = 'admin',
  },
  lspd_faggio = {
    name = 'lspd_faggio',
    brand = 'Emergency',
    model = 'lspd_faggio',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_faggio`,
    shop = 'admin',
  },
  doc_merit = {
    name = 'doc_merit',
    brand = 'Emergency',
    model = 'doc_merit',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `doc_merit`,
    shop = 'admin',
  },
  bbpr_rancher = {
    name = 'bbpr_rancher',
    brand = 'Emergency',
    model = 'bbpr_rancher',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_rancher`,
    shop = 'admin',
  },
  doc_riata = {
    name = 'doc_riata',
    brand = 'Emergency',
    model = 'doc_riata',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `doc_riata`,
    shop = 'admin',
  },
  lspd_shark = {
    name = 'lspd_shark',
    brand = 'Emergency',
    model = 'lspd_shark',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_shark`,
    shop = 'admin',
  },
  doc_stockade = {
    name = 'doc_stockade',
    brand = 'Emergency',
    model = 'doc_stockade',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `doc_stockade`,
    shop = 'admin',
  },
  lspd_tulip = {
    name = 'lspd_tulip',
    brand = 'Emergency',
    model = 'lspd_tulip',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_tulip`,
    shop = 'admin',
  },
  lspd_brigham = {
    name = 'lspd_brigham',
    brand = 'Emergency',
    model = 'lspd_brigham',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_brigham`,
    shop = 'admin',
  },
  cid_brigham = {
    name = 'cid_brigham',
    brand = 'Emergency',
    model = 'cid_brigham',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_brigham`,
    shop = 'admin',
  },
  cid_tulip = {
    name = 'cid_tulip',
    brand = 'Emergency',
    model = 'cid_tulip',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_tulip`,
    shop = 'admin',
  },
  sahp_greenwood = {
    name = 'sahp_greenwood',
    brand = 'Emergency',
    model = 'sahp_greenwood',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_greenwood`,
    shop = 'admin',
  },
  lspd_admiral = {
    name = 'lspd_admiral',
    brand = 'Emergency',
    model = 'lspd_admiral',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_admiral`,
    shop = 'admin',
  },
  lspd_greenwood = {
    name = 'lspd_greenwood',
    brand = 'Emergency',
    model = 'lspd_greenwood',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_greenwood`,
    shop = 'admin',
  },
  lspd_tornado = {
    name = 'lspd_tornado',
    brand = 'Emergency',
    model = 'lspd_tornado',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `lspd_tornado`,
    shop = 'admin',
  },
  sahp_brigham = {
    name = 'sahp_brigham',
    brand = 'Emergency',
    model = 'sahp_brigham',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_brigham`,
    shop = 'admin',
  },
  bcso_greenwood = {
    name = 'bcso_greenwood',
    brand = 'Emergency',
    model = 'bcso_greenwood',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_greenwood`,
    shop = 'admin',
  },
  bcso_voodoo = {
    name = 'bcso_voodoo',
    brand = 'Emergency',
    model = 'bcso_voodoo',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_voodoo`,
    shop = 'admin',
  },
  bcso_regina = {
    name = 'bcso_regina',
    brand = 'Emergency',
    model = 'bcso_regina',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bcso_regina`,
    shop = 'admin',
  },
  sahp_sparrow = {
    name = 'sahp_sparrow',
    brand = 'Emergency',
    model = 'sahp_sparrow',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `sahp_sparrow`,
    shop = 'admin',
  },
  bbpr_trike = {
    name = 'bbpr_trike',
    brand = 'Emergency',
    model = 'bbpr_trike',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `bbpr_trike`,
    shop = 'admin',
  },
  cid_admiral = {
    name = 'cid_admiral',
    brand = 'Emergency',
    model = 'cid_admiral',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `cid_admiral`,
    shop = 'admin',
  },
  ['do'] = {
    name = 'do',
    brand = 'Emergency',
    model = 'do',
    price = 100000,
    category = 'emergency',
    categoryLabel = 'Emergency',
    hash = `do`,
    shop = 'admin',
  },
  towtruck = {
    name = 'Large Towtruck',
    brand = 'Utility',
    model = 'towtruck',
    price = 100000,
    category = 'utility',
    categoryLabel = 'utility',
    hash = `towtruck`,
    shop = 'admin',
  },
  towtruck2 = {
    name = 'Small Towtruck',
    brand = 'Utility',
    model = 'towtruck2',
    price = 100000,
    category = 'utility',
    categoryLabel = 'utility',
    hash = `towtruck2`,
    shop = 'admin',
  },
}

for _, vehData in pairs(QBShared.Vehicles) do vehData.spawncode = vehData.model end
